/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AffectedResultResponse {
  affectedProjects: Array<string>
}

/** Discover projects in a workspace (Nx or Turborepo) */
export declare function discoverProjects(cwd: string): Array<NapiProject>

/** Find affected projects in a monorepo */
export declare function findAffected(options: FindAffectedOptions): AffectedResultResponse

export interface FindAffectedOptions {
  cwd: string
  base: string
  /** Head commit to compare (defaults to working tree) */
  head?: string
  projects: Array<NapiProject>
  enableProfiling?: boolean
  /** Lockfile change detection strategy: "none", "direct", "full" (default: "direct") */
  lockfileStrategy?: string
}

export interface NapiProject {
  name: string
  /** Project root directory (where project.json lives). Falls back to source_root if not set. */
  root?: string
  sourceRoot: string
  tsConfig?: string
  implicitDependencies: Array<string>
  targets: Array<string>
}
